### ISSUE TITLE
new installation today error

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit.mysociety.org#94]
When put ./manage.py syncdb

	(virtualenv-sayit) felipe@ACTASINTELIGENTES:~/sayit/sayit.mysociety.org$ ./manage.py syncdb
	Traceback (most recent call last):
	  File "./manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
		utility.execute()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
		self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
		self.execute(*args, **options.__dict__)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
		self.validate()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
		num_errors = get_validation_errors(s, app)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
		for (app_name, error) in get_app_errors().items():
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
		self._populate()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
		self.load_app(app_name, True)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
		models = import_module('%s.models' % app_name)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
		__import__(name)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/popolo/models.py", line 28, in <module>
		class Person(Dateframeable, Timestampable, models.Model):
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/popolo/models.py", line 77, in Person
		objects = PersonQuerySet.as_manager()
	AttributeError: type object 'PersonQuerySet' has no attribute 'as_manager'

**Comment by johnfelipe** [comment]
Then how solved?

**Comment by dracos** [comment]
This repository does not currently work with the current version of SayIt. It needs its dependencies updating for Django 1.8; you can either do that, or continue to use an older version of the SayIt package until that can be done.

**Comment by rdryan** [comment]
we get the same error.

Ryan

2016-04-06 21:41 GMT+08:00 M Somerville <notifications@github.com>:

**Comment by dracos** [comment]
Ryan – yes, sorry, as I say you have to currently use an older version of SayIt to use this repository. Using SayIt within your own Django project is fine, it is only this specific project, that uses SayIt to provide multi-instance hosting, that has an issue. There is a new PR at https://github.com/mysociety/sayit.mysociety.org/pull/95 which hopefully will fix most/all the issues for new installations.

**Comment by dracos** [comment]
This repository should now work again with the current version of SayIt.
